apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: 1.0.50   # (check latest version)
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: portainer.mydomain.com
              paths:
                - /
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

